// country_data.dart

/// A model class to hold a country's ISO 3166-1 alpha-2 code and its full,
/// locale-specific name for display.
class Country {
  final String code; // e.g., 'US' - Used for API calls and cookie storage.
  final String name; // e.g., 'United States of America' - Used for UI display.

  const Country({
    required this.code,
    required this.name,
  });
}

// ----------------------------------------------------------------------
// Source Data: The map used to generate the final list.
// Keys are the Country Codes (for logic), Values are the names (for display).
// ----------------------------------------------------------------------
const Map<String, String> _countryCodeToName = {
  "AF": "Afġānistān (Afghanistan)",
  "AL": "Shqipëria (Albania)",
  "DZ": "الجزائر / Lezzayer (Algeria)",
  "AD": "Principat d'Andorra (Andorra)",
  "AO": "Angola",
  "AG": "Antigua and Barbuda",
  "AR": "Argentina",
  "AM": "Հայաստան (Armenia)",
  "AU": "Australia",
  "AT": "Österreich (Austria)",
  "AZ": "Azərbaycan (Azerbaijan)",
  "BS": "The Bahamas (Bahamas)",
  "BH": "البحرين (Bahrain)",
  "BD": "বাংলাদেশ (Bangladesh)",
  "BB": "Barbados",
  "BY": "Беларусь (Belarus)",
  "BE": "België / Belgique / Belgien (Belgium)",
  "BZ": "Belize",
  "BJ": "Bénin (Benin)",
  "BT": "འབྲུག་ཡུལ་ (Bhutan)",
  "BO": "Bolivia (Bolivia (Plurinational State of))",
  "BA": "Bosna i Hercegovina (Bosnia and Herzegovina)",
  "BW": "Botswana",
  "BR": "Brasil (Brazil)",
  "BN": "Brunei Darussalam",
  "BG": "България (Bulgaria)",
  "BF": "Burkina Faso",
  "BI": "Burundi",
  "CV": "Cabo Verde",
  "KH": "កម្ពុជា (Cambodia)",
  "CM": "Cameroon / Cameroun (Cameroon)",
  "CA": "Canada",
  "CF": "République Centrafricaine (Central African Republic)",
  "TD": "Tchad / تشاد (Chad)",
  "CL": "Chile (Chile)",
  "CN": "中国 (China)",
  "CO": "Colombia",
  "KM": "Comores / جزر القمر (Comoros)",
  "CD": "Congo (Congo (Democratic Republic of the))",
  "CG": "Congo (Congo (Republic of the))",
  "CR": "Costa Rica",
  "CI": "Côte d'Ivoire",
  "HR": "Hrvatska (Croatia)",
  "CU": "Cuba",
  "CY": "Κύπρος / Kıbrıs (Cyprus)",
  "CZ": "Česko (Czechia)",
  "DK": "Danmark (Denmark)",
  "DJ": "Djibouti / جيبوتي",
  "DM": "Dominica",
  "DO": "República Dominicana (Dominican Republic)",
  "EC": "Ecuador",
  "EG": "مصر (Egypt)",
  "SV": "El Salvador",
  "GQ": "Guinea Ecuatorial (Equatorial Guinea)",
  "ER": "Ertra / إرتريا (Eritrea)",
  "EE": "Eesti (Estonia)",
  "SZ": "Eswatini",
  "ET": "ኢትዮጵያ (Ethiopia)",
  "FJ": "Viti (Fiji)",
  "FI": "Suomi (Finland)",
  "FR": "France",
  "GA": "Gabon",
  "GM": "The Gambia (Gambia)",
  "GE": "საქართველო (Georgia)",
  "DE": "Deutschland (Germany)",
  "GH": "Ghana",
  "GR": "Ελλάδα (Greece)",
  "GD": "Grenada",
  "GT": "Guatemala",
  "GN": "Guinée (Guinea)",
  "GW": "Guiné-Bissau (Guinea-Bissau)",
  "GY": "Guyana",
  "HT": "Ayiti (Haiti)",
  "VA": "Sancta Sedes (Holy See (Vatican City))",
  "HN": "Honduras",
  "HU": "Magyarország (Hungary)",
  "IS": "Ísland (Iceland)",
  "IN": "भारत (India)",
  "ID": "Indonesia",
  "IR": "ایران (Iran (Islamic Republic of))",
  "IQ": "العراق (Iraq)",
  "IE": "Éire (Ireland)",
  "IL": "ישראל (Israel)",
  "IT": "Italia (Italy)",
  "JM": "Jamaica",
  "JP": "日本 (Japan)",
  "JO": "الأردن (Jordan)",
  "KZ": "Қазақстан / Казахстан (Kazakhstan)",
  "KE": "Kenya",
  "KI": "Kiribati",
  "KP": "조선민주주의인민공화국 (Korea (Democratic People's Republic of))",
  "KR": "대한민국 (Korea (Republic of))",
  "KW": "الكويت (Kuwait)",
  "KG": "Кыргызстан (Kyrgyzstan)",
  "LA": "ສາທາລະນະລັດ ປະຊາທິປະໄຕ ປະຊາຊົນລາວ (Lao People's Democratic Republic)",
  "LV": "Latvija (Latvia)",
  "LB": "لبنان (Lebanon)",
  "LS": "Lesotho",
  "LR": "Liberia",
  "LY": "ليبيا (Libya)",
  "LI": "Liechtenstein",
  "LT": "Lietuva (Lithuania)",
  "LU": "Lëtzebuerg (Luxembourg)",
  "MG": "Madagasikara (Madagascar)",
  "MW": "Malawi",
  "MY": "Malaysia",
  "MV": "ދިވެހިރާއްޖެ (Maldives)",
  "ML": "Mali",
  "MT": "Malta",
  "MH": "Marshall Islands",
  "MR": "موريتانيا (Mauritania)",
  "MU": "Maurice (Mauritius)",
  "MX": "México (Mexico)",
  "FM": "Micronesia (Micronesia (Federated States of))",
  "MD": "Moldova (Moldova (Republic of))",
  "MC": "Monaco",
  "MN": "Монгол Улс (Mongolia)",
  "ME": "Црна Гора / Crna Gora (Montenegro)",
  "MA": "المغرب (Morocco)",
  "MZ": "Moçambique (Mozambique)",
  "MM": "မြန်မာ (Myanmar)",
  "NA": "Namibia",
  "NR": "Nauru",
  "NP": "नेपाल (Nepal)",
  "NL": "Nederland (Netherlands)",
  "NZ": "Aotearoa / New Zealand",
  "NI": "Nicaragua",
  "NE": "Niger",
  "NG": "Nigeria",
  "MK": "Македонија (North Macedonia)",
  "NO": "Norge (Norway)",
  "OM": "عمان (Oman)",
  "PK": "پاکستان (Pakistan)",
  "PW": "Palau",
  "PS": "فلسطين (Palestine (State of))",
  "PA": "Panamá (Panama)",
  "PG": "Papua New Guinea",
  "PY": "Paraguay",
  "PE": "Perú (Peru)",
  "PH": "Pilipinas (Philippines)",
  "PL": "Polska (Poland)",
  "PT": "Portugal",
  "QA": "قطر (Qatar)",
  "RO": "România (Romania)",
  "RU": "Россия (Russian Federation)",
  "RW": "Rwanda",
  "KN": "Saint Kitts and Nevis",
  "LC": "Saint Lucia",
  "VC": "Saint Vincent and the Grenadines",
  "WS": "Sāmoa (Samoa)",
  "SM": "San Marino",
  "ST": "São Tomé e Príncipe (Sao Tome and Principe)",
  "SA": "السعودية (Saudi Arabia)",
  "SN": "Sénégal (Senegal)",
  "RS": "Србија (Serbia)",
  "SC": "Sesel (Seychelles)",
  "SL": "Sierra Leone",
  "SG": "Singapore / Singapura / 新加坡 / சிங்கப்பூர",
  "SK": "Slovensko (Slovakia)",
  "SI": "Slovenija (Slovenia)",
  "SB": "Solomon Islands",
  "SO": "Soomaaliya (Somalia)",
  "ZA": "South Africa / uMzantsi Afrika / Suid-Afrika",
  "SS": "South Sudan",
  "ES": "España (Spain)",
  "LK": "ශ්‍රී ලංකා / இலங்கை (Sri Lanka)",
  "SD": "السودان (Sudan)",
  "SR": "Suriname",
  "SE": "Sverige (Sweden)",
  "CH": "Schweiz / Suisse / Svizzera / Svizra (Switzerland)",
  "SY": "سوريا (Syrian Arab Republic)",
  "TJ": "Тоҷикистон (Tajikistan)",
  "TZ": "Tanzania (Tanzania (United Republic of))",
  "TH": "ไทย (Thailand)",
  "TL": "Timór Lorosa'e (Timor-Leste)",
  "TG": "Togo",
  "TO": "Tonga",
  "TT": "Trinidad and Tobago",
  "TN": "تونس (Tunisia)",
  "TR": "Türkiye (Turkey)",
  "TM": "Türkmenistan (Turkmenistan)",
  "TV": "Tuvalu",
  "UG": "Uganda",
  "UA": "Україна (Ukraine)",
  "AE": "الإمارات العربية المتحدة (United Arab Emirates)",
  "GB": "United Kingdom (United Kingdom of Great Britain and Northern Ireland)",
  "US": "United States of America",
  "UY": "Uruguay",
  "UZ": "O‘zbekiston (Uzbekistan)",
  "VU": "Vanuatu",
  "VE": "Venezuela (Venezuela (Bolivarian Republic of))",
  "VN": "Việt Nam (Viet Nam)",
  "YE": "اليمن (Yemen)",
  "ZM": "Zambia",
  "ZW": "Zimbabwe",
};

// ----------------------------------------------------------------------
// FINAL EXPORTED LIST: The ultimate source for your dropdown UI.
// ----------------------------------------------------------------------

/// A constant list of all supported countries, pairing the code for logic
/// with the full name for the UI.
final List<Country> allCountries = _countryCodeToName.entries
    .map((entry) => Country(code: entry.key, name: entry.value))
    .toList()
// Optional: Sort by display name for a better user experience
  ..sort((a, b) => a.name.compareTo(b.name));