const List<String> countries = [
  "Afġānistān (Afghanistan)",
  "Shqipëria (Albania)",
  "الجزائر / Lezzayer (Algeria)",
  "Principat d'Andorra (Andorra)",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Հայաստան (Armenia)",
  "Australia",
  "Österreich (Austria)",
  "Azərbaycan (Azerbaijan)",
  "The Bahamas (Bahamas)",
  "البحرين (Bahrain)",
  "বাংলাদেশ (Bangladesh)",
  "Barbados",
  "Беларусь (Belarus)",
  "België / Belgique / Belgien (Belgium)",
  "Belize",
  "Bénin (Benin)",
  "འབྲུག་ཡུལ་ (Bhutan)",
  "Bolivia (Bolivia (Plurinational State of))",
  "Bosna i Hercegovina (Bosnia and Herzegovina)",
  "Botswana",
  "Brasil (Brazil)",
  "Brunei Darussalam",
  "България (Bulgaria)",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "កម្ពុជា (Cambodia)",
  "Cameroon / Cameroun (Cameroon)",
  "Canada",
  "République Centrafricaine (Central African Republic)",
  "Tchad / تشاد (Chad)",
  "Chile (Chile)",
  "中国 (China)",
  "Colombia",
  "Comores / جزر القمر (Comoros)",
  "Congo (Congo (Democratic Republic of the))",
  "Congo (Congo (Republic of the))",
  "Costa Rica",
  "Côte d'Ivoire",
  "Hrvatska (Croatia)",
  "Cuba",
  "Κύπρος / Kıbrıs (Cyprus)",
  "Česko (Czechia)",
  "Danmark (Denmark)",
  "Djibouti / جيبوتي",
  "Dominica",
  "República Dominicana (Dominican Republic)",
  "Ecuador",
  "مصر (Egypt)",
  "El Salvador",
  "Guinea Ecuatorial (Equatorial Guinea)",
  "Ertra / إرتريا (Eritrea)",
  "Eesti (Estonia)",
  "Eswatini",
  "ኢትዮጵያ (Ethiopia)",
  "Viti (Fiji)",
  "Suomi (Finland)",
  "France",
  "Gabon",
  "The Gambia (Gambia)",
  "საქართველო (Georgia)",
  "Deutschland (Germany)",
  "Ghana",
  "Ελλάδα (Greece)",
  "Grenada",
  "Guatemala",
  "Guinée (Guinea)",
  "Guiné-Bissau (Guinea-Bissau)",
  "Guyana",
  "Ayiti (Haiti)",
  "Sancta Sedes (Holy See (Vatican City))",
  "Honduras",
  "Magyarország (Hungary)",
  "Ísland (Iceland)",
  "भारत (India)",
  "Indonesia",
  "ایران (Iran (Islamic Republic of))",
  "العراق (Iraq)",
  "Éire (Ireland)",
  "ישראל (Israel)",
  "Italia (Italy)",
  "Jamaica",
  "日本 (Japan)",
  "الأردن (Jordan)",
  "Қазақстан / Казахстан (Kazakhstan)",
  "Kenya",
  "Kiribati",
  "조선민주주의인민공화국 (Korea (Democratic People's Republic of))",
  "대한민국 (Korea (Republic of))",
  "الكويت (Kuwait)",
  "Кыргызстан (Kyrgyzstan)",
  "ສາທາລະນະລັດ ປະຊາທິປະໄຕ ປະຊາຊົນລາວ (Lao People's Democratic Republic)",
  "Latvija (Latvia)",
  "لبنان (Lebanon)",
  "Lesotho",
  "Liberia",
  "ليبيا (Libya)",
  "Liechtenstein",
  "Lietuva (Lithuania)",
  "Lëtzebuerg (Luxembourg)",
  "Madagasikara (Madagascar)",
  "Malawi",
  "Malaysia",
  "ދިވެހިރާއްޖެ (Maldives)",
  "Mali",
  "Malta",
  "Marshall Islands",
  "موريتانيا (Mauritania)",
  "Maurice (Mauritius)",
  "México (Mexico)",
  "Micronesia (Micronesia (Federated States of))",
  "Moldova (Moldova (Republic of))",
  "Monaco",
  "Монгол Улс (Mongolia)",
  "Црна Гора / Crna Gora (Montenegro)",
  "المغرب (Morocco)",
  "Moçambique (Mozambique)",
  "မြန်မာ (Myanmar)",
  "Namibia",
  "Nauru",
  "नेपाल (Nepal)",
  "Nederland (Netherlands)",
  "Aotearoa / New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Македонија (North Macedonia)",
  "Norge (Norway)",
  "عمان (Oman)",
  "پاکستان (Pakistan)",
  "Palau",
  "فلسطين (Palestine (State of))",
  "Panamá (Panama)",
  "Papua New Guinea",
  "Paraguay",
  "Perú (Peru)",
  "Pilipinas (Philippines)",
  "Polska (Poland)",
  "Portugal",
  "قطر (Qatar)",
  "România (Romania)",
  "Россия (Russian Federation)",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Sāmoa (Samoa)",
  "San Marino",
  "São Tomé e Príncipe (Sao Tome and Principe)",
  "السعودية (Saudi Arabia)",
  "Sénégal (Senegal)",
  "Србија (Serbia)",
  "Sesel (Seychelles)",
  "Sierra Leone",
  "Singapore / Singapura / 新加坡 / சிங்கப்பூர",
  "Slovensko (Slovakia)",
  "Slovenija (Slovenia)",
  "Solomon Islands",
  "Soomaaliya (Somalia)",
  "South Africa / uMzantsi Afrika / Suid-Afrika",
  "South Sudan",
  "España (Spain)",
  "ශ්‍රී ලංකා / இலங்கை (Sri Lanka)",
  "السودان (Sudan)",
  "Suriname",
  "Sverige (Sweden)",
  "Schweiz / Suisse / Svizzera / Svizra (Switzerland)",
  "سوريا (Syrian Arab Republic)",
  "Тоҷикистон (Tajikistan)",
  "Tanzania (Tanzania (United Republic of))",
  "ไทย (Thailand)",
  "Timór Lorosa'e (Timor-Leste)",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "تونس (Tunisia)",
  "Türkiye (Turkey)",
  "Türkmenistan (Turkmenistan)",
  "Tuvalu",
  "Uganda",
  "Україна (Ukraine)",
  "الإمارات العربية المتحدة (United Arab Emirates)",
  "United Kingdom (United Kingdom of Great Britain and Northern Ireland)",
  "United States of America",
  "Uruguay",
  "O‘zbekiston (Uzbekistan)",
  "Vanuatu",
  "Venezuela (Venezuela (Bolivarian Republic of))",
  "Việt Nam (Viet Nam)",
  "اليمن (Yemen)",
  "Zambia",
  "Zimbabwe"
];